### ISSUE TITLE
💡 [REQUEST] - Add tooltips to extension

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#101]
### Summary

Add a tooltip to the globe toggle to explain what it does. The current implementation may be unintuitive because turning the toggle on actually turns the extension off on all platforms. It wouldn't make sense to switch it around either because then turning it on wouldn't mean that all platform toggles turn on. This will help clarify what the globe symbol means and what the toggle does before the user tries it out. 

Also, add a tooltip to each platform icon under "Enabled Sites". Some icons may not be obvious to users, especially when more (uncommon) social media platforms are added. For example, I didn't recognise the Imgur icon (now removed) when I first tried the extension.

### Basic Example

For the global tooltip, a message like "Disable everywhere" would be good. 
The tooltip for the sites should contain just the name of the platform.

**Comment by k1dubv1** [comment]
Approved
