### ISSUE TITLE
💡 [REQUEST] - Give allowed keywords a purpose

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#103]
### Summary

The allowed keywords currently do nothing. They are however saved and stored in Chrome Storage so it could be incorporated into the detection logic where if a post contains an allowed word, it will not be blurred (even when it contains a blocked word). This means users have more control over which posts they want or don't want to see. 

### Basic Example

Allowed words = ["chicken"]
Blocked words = ["dog", "cat"]

Post title = "dog befriends a chicken"

The post should not be blurred as the post title contains an allowed word, "chicken" (even though it also contains a blocked word, "dog").

### Drawbacks

This will allow posts containing the blocked words which may not be what the user expects. 

Some ideas to overcome this (will need further discussion with developers):
- Add tooltip
- Add (i) info button
- Add a help page/usage instructions when first installing the extension
- Add a FAQ section on the politicry.com website
- Rename "allowed" to something like "override" or "keep posts with..."

**Comment by k-yle** [comment]
great idea !
