### ISSUE TITLE
Update installation instructions to use release

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#113]
### Reference Issues
Related to #55 

### Summary
Add instructions for installing the latest release into a Chrome browser. 

Currently, the instructions require you to build the extension. Now that we have put out our first [release](https://github.com/se310-t6/politicry/releases), the installation instructions should also be updated. 

It will be simpler for new users to install it this way because they will not need to build the extension.

**Comment by Kanelmis** [comment]
Approve
