### ISSUE TITLE
[BUG] - Facebook support does not blur both description and image

### ISSUE THREAD

**Issue by Kanelmis** [se310-t6/politicry#115]
### Description

When detecting the description has the blocked word but not the image alt text, it only blurs the description text. When detecting that the image alt text has the blocked word but not the description, it only blurs the image. We want both image and description text to be blurred because they are likely to be related (and therefore unwanted).

### Reproduction steps

```bash
1. Install the extension.
2. Turn on the Facebook toggle.
3. Go to https://www.facebook.com/pizzahutnz/.
4. Find a post that contains the word "pizza" in either the image alt text or description (but not both).
5. Only one of (the image or description) will be blurred.
```

**Comment by Destiny-02** [comment]
Approved. Edited the issue description to add more detail.
