### ISSUE TITLE
💡 [REQUEST] - Introduce button hover states

### ISSUE THREAD

**Issue by k1dubv1** [se310-t6/politicry#116]
### Summary

The buttons in the extension currently are not very interactive. Adding hover states will improve the UI and indicate that the button is actually clickable. 

### Basic Example

"Edit Blocked" button changes colour/opacity/size when hovered over
"Save/cancel" buttons will also change colour/opacity/size
Links in text format will change colour, similar to the "Add other sites" link

### Drawbacks

Layout of the extension may need to be adjusted (but only minimal at most)
Need to introduce new colours to go with the colour scheme

**Comment by Destiny-02** [comment]
approved
