### ISSUE TITLE
[BUG] - Twitter logo is stretched

### ISSUE THREAD

**Issue by k1dubv1** [se310-t6/politicry#117]
### Description

The Twitter logo in the Politicry extension is currently stretched vertically. This should be changed so that it is at the normal image ratio

### Reproduction steps

```bash
1. Open the Politicry extension
```

### Screenshots

![image](https://user-images.githubusercontent.com/79814736/195963776-2d507a26-3202-41b2-8c1a-26aba9670eeb.png)

**Comment by Destiny-02** [comment]
approved
