### ISSUE TITLE
Create initial backend so frontend development can begin

### ISSUE THREAD

**Issue by JosiahBull** [se310-t6/politicry#13]
A quick and dirty backend needs to be created so that we have a board to bounce off for working on the front end.
I'm thinking something along the lines of
- [x] Write a swagger open api spec
  - [x] Endpoints to create user account
  - [x] Endpoints to get detections/upload detections
- [x] Setup the application with manually tested endpoints, text detection, etc 
- [x] Setup a simple database solution, and connect the app to it

Shouldn't take more than a day, and after that we'll need to add extensive testing, and probably switch to an application factory design for flask (or similar).

**Comment by Zasheus** [comment]
lgtm
