### ISSUE TITLE
Refactor backend to use application factory pattern

### ISSUE THREAD

**Issue by JosiahBull** [se310-t6/politicry#15]
The backend is currently quite generically implemented. It would be better to switch to a known pattern, e.g. the [application factory](https://flask.palletsprojects.com/en/2.2.x/patterns/appfactories/) pattern. 
At the same time it'll make sense to alter the database solution to a true ORM, such as flask-sqlalchemy. Furthermore, switching to application factory pattern should make testing much cleaner with pytest.

**Comment by Zasheus** [comment]
lgtm jo
