### ISSUE TITLE
Extension needs to parse items in feed on social media

### ISSUE THREAD

**Issue by JosiahBull** [se310-t6/politicry#16]
Currently the extension does nothing, a class needs to be developed to read data from popular sites, in some sort of generic way. It would be good for this class to be extensible in the future, so adding further media sites is simple.

Note that parsing functions need to extract:
- The raw URL of the media item
- The title of the post (if present)
- A reference to the top-level containing dom element, this is so we have a reference for hiding the entire post if required
- A reference to the <img> dom element, so we have a reference if we want to blur/change the image

Tasks:
- [ ] Create generic parsing class
- [ ] Create parsing function for Reddit
- [ ] Create parsing function for Imgur

**Comment by lche262** [comment]
lgtm!!
