### ISSUE TITLE
Basic Extension UI

### ISSUE THREAD

**Issue by JosiahBull** [se310-t6/politicry#17]
The chrome extension needs a very basic UI developed for it, so that when a user clicks on the extension icon in the toolbar there are some settings available. 

Such settings might include:
- [x] Disable/Enable for individual sites, and/or a global on/off for all sites
- [x] Changing the word "block list"
- [x] Changing the word "allow list"
- [x] Information on current version of the extension
- [x] Option to enable/disable connection to the backend
- [x] Links to our site/repo/wiki/etc

There's almost certainly something I've overlooked as I'm not much of a UI designer, so more/fewer items may be needed on the prior TODO list.

**Comment by lche262** [comment]
lgtm!
