### ISSUE TITLE
Report button on extension

### ISSUE THREAD

**Issue by JosiahBull** [se310-t6/politicry#19]
We need a way for users to notify us if a detection is missed, or incorrectly identified. 

This might appear as a small icon next to removed/replaced/blurred posts for users to click and report the false identification. 

Or, it might appear next to all posts so users can report any post they choose if it was a missed detection.

Not great at UI design thonks, so if someone else has a better idea for how the reporting of false/missed detections should work, input is greatly appreciated.

**Comment by lche262** [comment]
lgtm!
