### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by JosiahBull** [se310-t6/politicry#20]
Right now, the backend API has minimal test coverage (as of writing, none at all!).

It's important to bring this test coverage metric up, so that we can be confident our systems are working as intended.

- [x] Write test coverage for `backend`
- [x] Write test coverage for `website`
- [x] Write test coverage for `extension`
- [x] Setup codecov for all future requests
- [ ] Ensure test coverage is >80% going forwards

**Comment by lche262** [comment]
lgtm!

**Comment by k-yle** [comment]
re-opening, because tests are not complete for the extension worker
