### ISSUE TITLE
[BUG] - Deploying to production has serious problems

### ISSUE THREAD

**Issue by JosiahBull** [se310-t6/politicry#28]
### Description

Attempting to deploy to production highlighted several problematic configurations:
- [x] Api endpoint ports are misconfigured and unreachable
- [x] DB_PASSWORD needs to be passed through the api for the automatic connection script to function correctly
- [x] Some python packages need to be added to the `requirements.txt`
- [x] We should automatically build the backend package and save it on ghcr

### Reproduction steps

```bash
1. Try to deploy the api, and all these issues appear.
```

**Comment by hmin697** [comment]
nice!
