### ISSUE TITLE
💡 [REQUEST] - Add healthcheck to frontend and backend

### ISSUE THREAD

**Issue by JosiahBull** [se310-t6/politicry#41]
### Summary

In the event that either process crashes, autoheal can restart them. We should setup healthcheck commands to automatically check to see if the process has crashed.

### Basic Example

`HEALTHCHECK CMD curl --fail "http://${HOST}:${PORT}/healthcheck" || exit 1`

### Drawbacks

- Healthcheck commands can restart containers under high load, but not having crashed. This could take down infrastructure at inopportune times.
- Waste of CI/CD resources & power. Therefore this has a negative impact on the environment

**Comment by atan958** [comment]
lgtm!
