### ISSUE TITLE
Add new members to politicry.com

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#53]
### Summary

There are currently 5 profile cards as shown below. 
![image](https://user-images.githubusercontent.com/78716153/189630634-230f0f5e-70ba-4d78-b9e6-7f97fab1c3fc.png)

Add 4 more profile cards (will need to consult with teammates for the descriptive text and profile pictures). The descriptive text should be 3 lines high to match the other profile cards.
Since there is no more horizontal space to fit 4 more cards, refactor the cards to show in a horizontal scrolling pane. 

Remember to update the text in the footer to include our team name e.g. "Politicry by Team 4 and Team 6". 
![image](https://user-images.githubusercontent.com/78716153/189631088-3e3039a7-e774-476c-897f-ce2ecf3e4b86.png)

This feature is required to support the new team (and members) that will be contributing.

### Drawbacks

This will require changes/refactoring to the current layout container used by the profile cards.

**Comment by k1dubv1** [comment]
Approved

**Comment by Destiny-02** [comment]
Reopening issue as footer was missing in PR #61. `default.vue` was not committed for some reason 😕.
