### ISSUE TITLE
[BUG] - The profile cards on politicry.com are not the same size

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#54]
### Description

The profile cards are of different heights. In particular, the profile card for Leonard Min is noticeably taller than the rest. This is due to the height of the images. All the description texts are 3 lines. 

### Reproduction steps

```bash
1. Go to politicry.com
2. Scroll down to the profile cards
3. See profile card heights
```

### Screenshots

![image](https://user-images.githubusercontent.com/78716153/189633397-edd76aea-4525-4633-a2ff-eedb4096e80b.png)

**Comment by k1dubv1** [comment]
Approved

**Comment by k1dubv1** [comment]
![image](https://user-images.githubusercontent.com/79814736/189843010-98f14d43-f96e-4a93-a523-e2ef7783a558.png)
Note that some devices show a different number of lines for the description at 100% zoom and also show names on multiple lines due to varying device screen resolution
