### ISSUE TITLE
[BUG] - Development/Deployment instructions are incorrect

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#56]
### Description

The instructions should work for all (or most) operating systems. Currently, the commands are Linux-specific. 
Additionally, some commands should have prerequisites detailing what tools should already be installed e.g. docker, yarn.
Some commands do not work in the backend folder. Fixing this may require changes to the gitignore. 

(optional) Include recommendations for the IDE and extensions. 

### Reproduction steps

```bash
1. Go to https://github.com/se310-t6/politicry
2. Download or clone the repository
3. Scroll down to the README
4. Follow the development/deployment steps
5. Using the commands as instructed should result in errors
```

### Logs
The error messages you receive depend on your operating system and the tools you have installed. Below is one example. 

```bash
PS C:\Users\desti\Documents\GitHub\politicry> cd .\backend\
PS C:\Users\desti\Documents\GitHub\politicry\backend> docker-compose -f docker-compose.dev.yml up -d
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '.\\docker-compose.dev.yml'
```

**Comment by k1dubv1** [comment]
Approved
