### ISSUE TITLE
Setup Wiki

### ISSUE THREAD

**Issue by JosiahBull** [se310-t6/politicry#6]
Setup the wiki for this repository

**Comment by hmin697** [comment]
great!

**Comment by lche262** [comment]
I set up the wiki of the page, but we need to update some of the links and polish the details in the future, we can check the wiki page from [here](https://github.com/se310-t6/politicry/wiki)

**Comment by JosiahBull** [comment]
I had a look at it, and it looks really good to me. Nice work! :D
