### ISSUE TITLE
Link UI Elements

### ISSUE THREAD

**Issue by k1dubv1** [se310-t6/politicry#68]
Link the following buttons/elements to their respective web pages:

"Version 1.0.0" -> https://politicry.com/
"Full Docs" -> https://se310-t6.github.io/politicry/
"Add other sites" -> https://github.com/se310-t6/politicry/issues

Currently these elements do not redirect to anywhere.

**Comment by Destiny-02** [comment]
I consider this a bug because clicking on the links produces unexpected behaviour. All bugs should follow the bug issue template set up by the previous group. This will help ensure consistency. 

#54 and #56 are some examples.
