### ISSUE TITLE
[BUG] - Buttons/elements do not redirect to other pages

### ISSUE THREAD

**Issue by k1dubv1** [se310-t6/politicry#69]
### Description

Some buttons in the extension do not redirect anywhere when clicked. These need to be implemented.

### Reproduction steps

```bash
1. Open the extension
2. Click any of the following
 - Version 1.0.0 info button
 - "Full Docs"
 - "Add Other Sites"
 - The Politicry logo
```

**Comment by Destiny-02** [comment]
approved

**Comment by k1dubv1** [comment]
![image](https://user-images.githubusercontent.com/79814736/191716412-d0202172-8306-48a2-a6f1-0be87f51dd0f.png)
I've noticed that the logo is also a link (which should lead to the website), should the version information button link to the GitHub repository (Which is the same link as "full docs") or somewhere else? I don't think it had a link before (unless I'm mistaken)

**Comment by Destiny-02** [comment]
> ![image](https://user-images.githubusercontent.com/79814736/191716412-d0202172-8306-48a2-a6f1-0be87f51dd0f.png) I've noticed that the logo is also a link (which should lead to the website), should the version information button link to the GitHub repository (Which is the same link as "full docs") or somewhere else? I don't think it had a link before (unless I'm mistaken)

I think either options make sense. Personally, I prefer just linking the (i). I don't think it would be a good idea for the Version and (i) to link to 2 different places since they are placed quite closely on the UI.
