### ISSUE TITLE
💡 [REQUEST] - Make filter chips editable

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#71]
### Summary

The filter chips are currently not editable. There exists a "Edit Allowed" and "Edit Blocked" button, but it does not work. Implementing this will help users customise what posts are blurred on their feed. 
![image](https://user-images.githubusercontent.com/78716153/191136715-54704fed-101a-4817-8ce6-0a15076f1798.png)

### Basic Example

When the "Edit Allowed"/"Edit Blocked" button is clicked, the chips should be replaced by an editable text area. The text area should contain a list of comma-separated values, representing the chip names. The "Edit Allowed" / "Edit Blocked" button should be replaced with two smaller buttons "Save" and "Cancel". 

### Drawbacks

N/A

### Unresolved questions

I'm not sure if the current detection logic is actually based on the allowed/blocked list of words or hardcoded. This is a separate matter so if it turns out that the detection logic is not dynamic, a separate issue should be created for this.

**Comment by k-yle** [comment]
approved
