### ISSUE TITLE
Remove unnecessary placeholders in the extension pop up page

### ISSUE THREAD

**Issue by Kanelmis** [se310-t6/politicry#73]
### Summary

No logic has been implemented for the "Connect to our backend" placeholder section, so this placeholder should be removed.

### Basic Example

The extension will look the same minus the "Connect to our backend" section.

### Drawbacks

The extension might look more incomplete or like it has fewer features. I think having a simpler design is better than having "fake" features.

### Unresolved questions
It is not clear what connecting to the backend should do or how to do it. If this is clarified, a feature request can be made for it.

### Screenshot
<img width="384" alt="截屏2022-09-21 下午6 13 48" src="https://user-images.githubusercontent.com/37644658/191427884-2eb70d17-4cd3-44d5-bfe8-7cd146d54832.png">

**Comment by Destiny-02** [comment]
approved
