### ISSUE TITLE
💡 [REQUEST] - Introduce a code formatter and linting tool

### ISSUE THREAD

**Issue by k-yle** [se310-t6/politicry#74]
### Summary

Currently there are various different code and indentation styles. To improve maintainability, we should use a unified format across all files. 

### Basic Example

Some examples of errors that would have been picked up by a lint tool: 
 - [invalid html tags](https://github.com/se310-t6/politicry/blob/bd67a08/backend/static/notfound.html#L11)
 - [undefined variable i](https://github.com/se310-t6/politicry/blob/1ecb1c4/extension/public/reddit.js#L65)

### Drawbacks

- more complicated to set up the development environment, since we would need to install 1 or 2 vscode extensions (prettier and/or eslint)

**Comment by Destiny-02** [comment]
Approved. Removed labels as none of them really fit this kind of request.
