### ISSUE TITLE
[BUG] - Sonarcloud configuration isn't quite right

### ISSUE THREAD

**Issue by k-yle** [se310-t6/politicry#75]
### Description

There are some issues with the sonarcloud set up
 - code coverage is not being collected at all
 - code coverage is only being generated for the backend, not the frontend or extension
 - the quality gate has not been configured
 - the number of code smells in the mainline branch is not easily visible from github, so there are many warnings
 - warnings from flake8 and eslint do not show up in sonarcloud
 - eslint can be removed once sonarlint & sonarcloud are set up correctly, since it will be redundant. See [comment #r978538554](https://github.com/se310-t6/politicry/pull/78#discussion_r978538554) and [comment #r979342297](https://github.com/se310-t6/politicry/pull/81#discussion_r979342297)
 
### Reproduction URL

https://sonarcloud.io/summary/overall?id=se310-t6_politicry

### Reproduction steps

```bash
1. Go to https://sonarcloud.io/summary/overall?id=se310-t6_politicry
2. Note how the issues mentioned above are noticable.
```

### Screenshots

```bash
N/A
```

### Logs

```bash
N/A
```

**Comment by Destiny-02** [comment]
Approved. This will expose a lot of the test coverage and code smells that were overlooked during development in A1.

**Comment by k-yle** [comment]
we don't have access to the sonarcloud configuration, so this issue is waiting on a reply from team 6

**Comment by k-yle** [comment]
reopening, #94 didn't fully fix the issue
