### ISSUE TITLE
[BUG] - Reddit, Twitter and Instagram are not used blockedWords from Chrome Storage

### ISSUE THREAD

**Issue by k-yle** [se310-t6/politicry#82]
### Description

The words that the user configures in the chrome extension popup are not used by the filters for Reddit, Instagram and Twitter. 

We should use `chrome.storage.sync.get(["blockedWords"], ...` to get the configured words. 

### Reproduction URL

N/A

### Reproduction steps

```bash
1. Set a custom word in the extension popup
2. open a post which contains that word
3. note how it's not blurred
```

### Screenshots

![image](https://user-images.githubusercontent.com/16009897/192125376-4da94814-6376-45b1-ba3c-f390067b5845.png)

**Comment by Destiny-02** [comment]
Approved. Updated the issue to include Reddit as well.
