### ISSUE TITLE
[BUG] - Warning when adding the extension to browser

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#83]
### Description

There is a warning "'page_action' requires manifest version of 2 or lower." when you add the extension to your browser. 

### Reproduction steps

```bash
1. Follow the README instructions to install the extension 
2. Click on the Errors button in the extension card
3. There should be a warning saying "'page_action' requires manifest version of 2 or lower."
```

### Screenshots
![image](https://user-images.githubusercontent.com/78716153/192132567-3e1f7eb0-accf-417a-860c-1c34cda8ac14.png)

### Potential Fix
The `manifest_version` is 3 while `page_action` is not supported in version 2. 
Move everything under `page_action` into `action` in the extension `manifest.json` file. 
Source: https://stackoverflow.com/questions/63308160/how-to-migrate-manifest-version-2-to-v3-for-chrome-extension

**Comment by k-yle** [comment]
approved. i can also reproduce this bug
