### ISSUE TITLE
[BUG] - Saving a very long keyword extends past the extension UI boundaries

### ISSUE THREAD

**Issue by Kanelmis** [se310-t6/politicry#85]
### Description

Saving a very long keyword extends past the extension UI boundaries. Should truncate and add a `...` ellipsis to the keyword when displaying the tag text.

### Reproduction steps

```bash
1. Open the extension
2. Click on 'Edit Allowed' button
3. Enter a very long keyword. E.g.'efafafafafafafaaffafafafaf'
4. Click on 'Save' button
5. See error
```

### Screenshots

<img width="223" alt="截屏2022-09-25 下午8 45 24" src="https://user-images.githubusercontent.com/37644658/192133583-c7abbef2-4420-4883-99a0-7b7b07b0b039.png">

**Comment by Destiny-02** [comment]
approved, edited for clarity
