### ISSUE TITLE
[BUG] - Deleting all blocked words causes the default tags to appear again. 

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#89]
### Description

When user deletes all the blocked words, no tags should show. However, when all the words are deleted, the default list shows instead. The initial blocked words list can still be the default list containing "ukraine", "terrorist" etc..

### Reproduction steps

```bash
1. Open the extension
2. Open the blocked words tab
3. Click "Edit Blocked"
4. Delete all the words in the list
5. Click "Save"
6. The default list (starting with "ukraine" ...) will show
```

### Screenshots
![image](https://user-images.githubusercontent.com/78716153/192669085-c65e8860-b912-432b-a961-4ec6bff25d6f.png)

**Comment by k-yle** [comment]
approved. this relates to https://github.com/se310-t6/politicry/pull/86#pullrequestreview-1119384359
