### ISSUE TITLE
💡 [REQUEST] - Make Blocked words tab enabled by default on UI

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#90]
### Summary

Make the blocked words show by default when opening the extension instead of the allowed words. Users would have installed this extension to block out certain content so they are more likely to want to see the blocked list of keywords first. 

![image](https://user-images.githubusercontent.com/78716153/192669498-1873deca-8fde-41e4-9967-11810d85f617.png)

### Basic Example

The Blocked tab should be open every time the extension is opened. The order of the allowed and blocked tabs will stay the same ("Allowed" on the left and "Blocked" on the right). The correct list of keywords and correct edit button should also display. 

### Drawbacks

Usually, the option on the left is enabled first. However, if we switch the order, another convention will be broken where the positive action should be first, then negative action. E.g. "Yes" and "No", rather than "No" and "Yes". So, I think it makes more sense to have "Blocked" enabled by default rather than switch them around.

**Comment by k1dubv1** [comment]
Approved
