### ISSUE TITLE
[REFACTOR] - Use relative positioning instead of absolute positioning in the extension UI

### ISSUE THREAD

**Issue by Destiny-02** [se310-t6/politicry#96]
### Summary
Many components in the extension UI currently uses absolute positioning (and fixed width/height). This means additions to the UI in the future will be difficult and more manual. I imagine one would need to use a "trial-and-error" approach on the pixel positioning of the new component. 

This may not have been a problem in the past as the design has remained relatively constant. There also has been no need to support different screen sizes because the extension pop-up dimensions is fixed. 

### Benefits
- Better control over padding/margin values
- Improve modifiability, such as adding new UI components
- Improve readability - it is easier to tell where things should appear in the pop-up just by looking at the code
- Incorrect positioning (e.g. off-by-one pixel) may be discovered and fixed during the refactoring 

### Drawbacks
- It will take some time to decide on which CSS properties to use (it is more straightforward/easier to just add `top`/`left` properties)
- It is hard to write tests for this as we would need to test if the UI components are still in the same place when rendered. There is the option of snapshot testing, but this might be out of scope for this last assignment (we are only required to create tests for functional changes). 
- It may require changes to `popup.html` and `popup.js`.

**Comment by k1dubv1** [comment]
Approved
