### ISSUE TITLE
[BUG] - Extension does not blur images on Twitter

### ISSUE THREAD

**Issue by k1dubv1** [se310-t6/politicry#97]
### Description

Media such as images, gifs and video are not being blurred in tweets. Only text is currently being blurred.

### Reproduction steps

```bash
1. Add words to Politicry blocked list
2. Enable Politicry for Twitter
3. Go to https://twitter.com/explore
4. Search a hashtag that may contain tweets relevant to the blocked words
```

### Screenshots

![image](https://user-images.githubusercontent.com/79814736/193556227-b860e869-1ecb-4aa2-89a6-632b0c75f18f.png)

**Comment by Destiny-02** [comment]
approved
