### ISSUE TITLE
💡 [REQUEST] - Improve reporting feature

### ISSUE THREAD

**Issue by k-yle** [se310-t6/politicry#99]
### Summary

Currently the report button link to the repository's issue tracker. Most users will not be familar with GitHub or know how to properly create an issue. Instead, the report button could link to a new window pop up window or page e.g. politicry.com/report. The input fields could be automatically filled some information such as the URL they were on and list of allowed/blocked words that were saved. 

### Basic Example

N/A

### Drawbacks

None	

### Unresolved questions

None

**Comment by Destiny-02** [comment]
approved
